// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcehevuoaxvfpbzfsehr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZWhldnVvYXh2ZnBiemZzZWhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNjIxMTUsImV4cCI6MjA1ODYzODExNX0.xotVC4X3L4gUYHyba2dZqSZbUeAjwyHf5rT3iQZzozc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);